#!/bin/bash
# Script to help manually compare colors with Material Theme Builder
#
# This script provides instructions and URLs for manual comparison

echo "==================================================================="
echo "Material Theme Builder Color Comparison Guide"
echo "==================================================================="
echo ""
echo "Source Color: #769CDF"
echo "Scheme: Tonal Spot"
echo "Contrast: 0 (standard)"
echo "Color Match: false (unchecked)"
echo ""
echo "Step 1: Open Material Theme Builder"
echo "---------------------------------------"
echo "URL: https://material-foundation.github.io/material-theme-builder/"
echo ""
echo "Step 2: Configure the theme"
echo "---------------------------------------"
echo "1. Click on the color picker for 'Primary' color"
echo "2. Enter the hex value: 769CDF (without #)"
echo "3. Ensure 'Tonal Spot' scheme is selected (it's the default)"
echo "4. Keep contrast at 0 (standard)"
echo "5. Keep 'Color match - Stay true to my color inputs' UNCHECKED"
echo ""
echo "Step 3: Take a screenshot"
echo "---------------------------------------"
echo "Take a full-page screenshot showing all color roles:"
echo "  - Primary, Secondary, Tertiary colors"
echo "  - Container colors"
echo "  - Surface colors and variants"
echo "  - Error colors"
echo "  - Fixed colors"
echo "  - Outline colors"
echo ""
echo "Step 4: Compare with Storybook"
echo "---------------------------------------"
echo "Storybook URL: http://localhost:6006/?path=/story/mcu--st-1"
echo ""
echo "Compare the generated colors between both screenshots."
echo ""
echo "==================================================================="
echo "Expected Result: Colors should match exactly or be very similar"
echo "==================================================================="
