# GitHub Copilot Coding Agent allowlist configuration
# This allows the agent to access external domains during runtime (after firewall is enabled)
# For accessing external websites to take screenshots, fetch data, or interact with web resources
#
# The allowlist starts with specific, commonly-used domains and ends with a wildcard
# to enable unrestricted internet access for maximum flexibility in future sessions.

allowlist:
  # Material Design and related resources
  - material-foundation.github.io
  - m3.material.io
  - material.io
  
  # General web access patterns (common domains)
  - '*.github.io'
  - '*.githubusercontent.com'
  - github.com
  
  # Common CDNs and resources
  - cdn.jsdelivr.net
  - unpkg.com
  - esm.sh
  
  # Package registries
  - registry.npmjs.org
  - registry.yarnpkg.com
  
  # Storybook resources
  - storybook.js.org
  - '*.chromatic.com'
  
  # Development and documentation sites
  - developer.mozilla.org
  - stackoverflow.com
  
  # SECURITY NOTE: Wildcard entry for unrestricted access
  # This allows the agent to access ANY external website for screenshots and web fetching.
  # While this poses security implications, it's required for the requested use case of
  # taking screenshots of arbitrary external websites in future Copilot sessions.
  # Repository administrators should review and approve this configuration.
  - '*'
