# GitHub Copilot Coding Agent setup steps
# These steps run before the firewall is enabled, allowing the agent to access external resources
# Documentation: https://docs.github.com/en/copilot/customizing-copilot/using-github-copilot-coding-agent-in-your-repository

steps:
  # Setup pnpm package manager
  - uses: pnpm/action-setup@v4

  # Setup Node.js with caching
  - uses: actions/setup-node@v6
    with:
      node-version-file: ".nvmrc"
      cache: "pnpm"

  # Install dependencies before firewall is enabled
  # This allows access to npm registry and any external resources needed during installation
  - run: pnpm install --frozen-lockfile
