import type { Meta, StoryObj } from "@storybook/react-vite";
import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeTonalSpot,
  MaterialDynamicColors,
} from "@material/material-color-utilities";
import { kebabCase } from "lodash-es";
import { tokenNames } from "./Mcu";

const meta = {
  title: "Mcu/Color Comparison",
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

// Generate colors using Material Color Utilities the way Material Theme Builder does
function generateMaterialThemeBuilderColors(
  sourceHex: string,
  isDark: boolean,
) {
  const sourceArgb = argbFromHex(sourceHex);
  const hct = Hct.fromInt(sourceArgb);
  const scheme = new SchemeTonalSpot(hct, isDark, 0); // Using TonalSpot with contrast 0

  const colors: Record<string, string> = {};
  tokenNames.forEach((tokenName) => {
    const dynamicColor = MaterialDynamicColors[tokenName];
    const argb = dynamicColor.getArgb(scheme);
    colors[tokenName] = hexFromArgb(argb);
  });

  return colors;
}

function ColorBox({
  name,
  color,
  textColor,
}: {
  name: string;
  color: string;
  textColor?: string;
}) {
  return (
    <div
      style={{
        backgroundColor: color,
        color: textColor || "white",
        padding: "0.5rem",
        outline: "1px solid #ccc",
        fontSize: "0.75rem",
        fontFamily: "sans-serif",
        mixBlendMode: "difference",
        minHeight: "60px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
      }}
    >
      <div style={{ fontWeight: "bold" }}>{name}</div>
      <div style={{ fontSize: "0.65rem", opacity: 0.8 }}>{color}</div>
    </div>
  );
}

function ComparisonView({ sourceColor }: { sourceColor: string }) {
  // Generate colors from Material Theme Builder (light mode)
  const mtbColors = generateMaterialThemeBuilderColors(sourceColor, false);

  return (
    <div style={{ padding: "2rem" }}>
      <h1 style={{ fontFamily: "sans-serif", marginBottom: "2rem" }}>
        Color Comparison: Default Story vs Material Theme Builder
      </h1>
      <p style={{ fontFamily: "sans-serif", marginBottom: "1rem" }}>
        Source Color: <strong>{sourceColor}</strong>
      </p>
      <p
        style={{
          fontFamily: "sans-serif",
          marginBottom: "2rem",
          color: "#666",
        }}
      >
        This comparison shows the colors generated by the Material Color
        Utilities library using the same method as Material Theme Builder
        (TonalSpot scheme with 0 contrast).
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "200px 1fr",
          gap: "1rem",
          marginBottom: "3rem",
        }}
      >
        <div
          style={{
            fontWeight: "bold",
            fontFamily: "sans-serif",
            padding: "0.5rem",
          }}
        >
          Color Role
        </div>
        <div
          style={{
            fontWeight: "bold",
            fontFamily: "sans-serif",
            padding: "0.5rem",
          }}
        >
          Material Theme Builder Reference
        </div>

        {Object.entries(mtbColors).map(([name, color]) => (
          <div
            key={name}
            style={{
              display: "contents",
            }}
          >
            <div
              style={{
                fontFamily: "sans-serif",
                padding: "0.5rem",
                fontSize: "0.875rem",
              }}
            >
              {kebabCase(name)}
            </div>
            <ColorBox name={name} color={color} />
          </div>
        ))}
      </div>

      <div
        style={{
          marginTop: "3rem",
          padding: "1rem",
          backgroundColor: "#f5f5f5",
          borderRadius: "8px",
        }}
      >
        <h2 style={{ fontFamily: "sans-serif", marginBottom: "1rem" }}>
          How to Compare
        </h2>
        <ol style={{ fontFamily: "sans-serif", lineHeight: "1.6" }}>
          <li>
            Open the "Default" story in the sidebar to see the current
            implementation
          </li>
          <li>
            Compare the color values shown in that story with the values shown
            here
          </li>
          <li>
            You can also verify these colors by visiting{" "}
            <a
              href="https://material-foundation.github.io/material-theme-builder/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Material Theme Builder
            </a>{" "}
            and entering the source color #{sourceColor.replace("#", "")}
          </li>
        </ol>
      </div>
    </div>
  );
}

export const CompareWithMTB: Story = {
  name: "Compare with Material Theme Builder",
  render: () => <ComparisonView sourceColor="#769CDF" />,
};
